# Generated by Django 5.1.5 on 2025-01-19 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_menu_price_alter_order_table_name'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='menu',
            table='menu',
        ),
    ]
