# Generated by Django 5.1.5 on 2025-01-19 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_menu_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'verbose_name': 'menu', 'verbose_name_plural': 'menu'},
        ),
        migrations.RenameField(
            model_name='order',
            old_name='table_name',
            new_name='table_number',
        ),
    ]
