# Generated by Django 5.1.5 on 2025-01-19 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_menu_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_price',
            field=models.IntegerField(default=0, editable=False, verbose_name='Total Price (₽)'),
            preserve_default=False,
        ),
    ]
