# Generated by Django 5.1.5 on 2025-01-19 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_order_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_price',
        ),
    ]
